function baselines = ais_baseline_olustur(X)
    % Classification Learner export formatindan AIS baseline'larini olusturur
    % Giriş:
    %   X: Ozellik matrisi, boyuta gore baseline degerleri ayarlanir
    % Çıkış:
    %   baselines: Model bazli baseline struct dizisi

    n_ozellik = size(X, 2);
    subspace_dimension = max(1, min(15, n_ozellik - 1));

    baselines = repmat(struct(...
        'model_adi', '', ...
        'model_tipi', '', ...
        'parametreler', struct(), ...
        'aranacak_alanlar', {{}}, ...
        'sinirlar', struct()), 4, 1);

    baselines(1).model_adi = 'SVM';
    baselines(1).model_tipi = 'svm';
    baselines(1).parametreler = struct(...
        'KernelFunction', 'gaussian', ...
        'KernelScale', 5.5, ...
        'BoxConstraint', 1);
    baselines(1).aranacak_alanlar = {'BoxConstraint', 'KernelFunction', 'KernelScale'};
    baselines(1).sinirlar = struct('BoxConstraint', [0.01 100], 'KernelScale', [0.001 10]);

    baselines(2).model_adi = 'Ensemble';
    baselines(2).model_tipi = 'ensemble';
    baselines(2).parametreler = struct(...
        'Method', 'Subspace', ...
        'NumLearningCycles', 30, ...
        'Learners', 'knn', ...
        'NPredToSample', subspace_dimension);
    baselines(2).aranacak_alanlar = {'NumLearningCycles', 'NPredToSample'};
    baselines(2).sinirlar = struct('NumLearningCycles', [10 200], 'NPredToSample', [1 subspace_dimension]);

    baselines(3).model_adi = 'MLP';
    baselines(3).model_tipi = 'mlp';
    baselines(3).parametreler = struct(...
        'LayerSizes', 100, ...
        'Activations', 'relu', ...
        'Lambda', 0, ...
        'IterationLimit', 1000);
    baselines(3).aranacak_alanlar = {'LayerSizes', 'Activations', 'Lambda', 'IterationLimit'};
    baselines(3).sinirlar = struct('LayerSizes', [10 100], 'Lambda', [0 1], 'IterationLimit', [200 2000]);

    baselines(4).model_adi = 'KNN';
    baselines(4).model_tipi = 'knn';
    baselines(4).parametreler = struct(...
        'Distance', 'Euclidean', ...
        'Exponent', [], ...
        'NumNeighbors', 10, ...
        'DistanceWeight', 'SquaredInverse');
    baselines(4).aranacak_alanlar = {'NumNeighbors', 'Distance', 'DistanceWeight'};
    baselines(4).sinirlar = struct('NumNeighbors', [1 50]);
end