% k-En Yakin Komsu (KNN) siniflandiricisi
classificationKNN = fitcknn(...
    Egitim, ...
    Egitimc, ...
    'Distance', 'Cosine', ...
    'Exponent', [], ...
    'NumNeighbors', 10, ...
    'DistanceWeight', 'Equal', ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);

% Test veri seti uzerinde tahmin yapimi
Test_tahmin_knn=predict(classificationKNN,Test);

% Karmasiklasma matrisi gosterimi
plotconfusion(Test_tahmin_knn',Testc');
rng('default')