% Yapay Sinir Agi (Neural Network) siniflandiricisi
classificationNeuralNetwork = fitcnet(...
    Egitim, ...
    Egitimc, ...
    'LayerSizes', 10, ...
    'Activations', 'relu', ...
    'Lambda', 0, ...
    'IterationLimit', 1000, ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);

% Test veri seti uzerinde tahmin yapimi
Test_tahmin_NN=predict(classificationNeuralNetwork,Test);

% Karmasiklasma matrisi gosterimi
plotconfusion(Test_tahmin_NN',Testc');
rng('default')