% Destek Vektor Makinasi (SVM) siniflandiricisi
classificationSVM = fitcsvm(...
    Egitim, ...
    Egitimc, ...
    'KernelFunction', 'linear', ...
    'PolynomialOrder', [], ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true, ...
    'ClassNames', [0; 1]);

% Test veri seti uzerinde tahmin yapimi
Test_tahmin=predict(classificationSVM,Test);

% Karmasiklasma matrisi gosterimi
plotconfusion(Test_tahmin',Testc');
rng('default')