% Karar Agaci (Decision Tree) siniflandiricisi
classificationTree = fitctree(...
    Egitim, ...
    Egitimc, ...
    'SplitCriterion', 'gdi', ...
    'MaxNumSplits', 100, ...
    'Surrogate', 'off', ...
    'ClassNames', [0; 1]);

% Test veri seti uzerinde tahmin yapimi
Test_tahmin_tree=predict(classificationTree,Test);

% Karmasiklasma matrisi gosterimi
plotconfusion(Test_tahmin_tree',Testc');
rng('default')